### ISSUE TITLE
GUI - 3 useful options that don't work

### ISSUE THREAD

**Issue by KariRudjord** [snaekobbi/pipeline-mod-nlb#48] opened 2016-05-24 11:01 UTC
- [x] Text elements:    Include note references – should be able to exclude them as well (unable option)
- [x] Numbering: Show braille page number – should be able to leave out numbering as well (unable option)
- [x] Placement of content: Placement of colophone – should be able to move it to the end of book

@usama49 @josteinaj @bertfrees

**Comment by bertfrees** [comment] 2016-05-24 11:50
Thanks Kari!

All of these options should be possible to implement with SASS. @usama49 This is already on your to do list, right? It is more or less a duplicate of https://github.com/snaekobbi/pipeline-mod-nlb/issues/42, which I have included in https://github.com/snaekobbi/sprints/issues/200.

**Comment by josteinaj** [comment] 2016-11-17 12:42
@usama49: we marked this as "done". Is that right? Can we close this issue?

**Comment by usama49** [comment] 2016-11-25 07:33
yes done. Please close it.

**Comment by josteinaj** [comment] 2016-11-25 10:01
Good

**Closed as completed by josteinaj** 2016-11-25 10:01 UTC
Labels: 4 - Done
